package dump

import (
	"cdump/config"
	"cdump/schema"
	"database/sql"
	"fmt"
	"log"
	"os"
	"regexp"
	"sort"
	"strings"
	"time"
)

const batchSize = 100

// serialPlaceholder is the magic value in config that triggers per-row serial generation.
const serialPlaceholder = "__CDUMP_SERIAL__"

// WriteDataSQL generates data.sql with INSERT statements for all tables.
//   - Tables with a (direct or indirect) FK path to userTable are filtered:
//     only rows reachable from the kept users are included.
//   - Tables with no FK path to userTable are fully copied.
func WriteDataSQL(
	path string,
	originDB *sql.DB,
	dbName string,
	tables []string,
	g *schema.Graph,
	userTable string,
	userColumn string,
	keepUsers []string,
	excludeFields []config.ExcludeField,
	replaceFields []config.ReplaceField,
	emptyPatterns []*regexp.Regexp,
) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating %s: %w", path, err)
	}
	defer f.Close()

	fmt.Fprintln(f, "-- Generated by cdump")
	fmt.Fprintln(f, "SET FOREIGN_KEY_CHECKS=0;")
	fmt.Fprintln(f, "SET NAMES utf8mb4;")
	fmt.Fprintln(f)

	// Find which tables depend on userTable (directly or indirectly).
	depLevels := schema.FindDependentTables(g, userTable)

	// Get PK columns for userTable.
	userPKs, err := schema.GetPrimaryKeys(originDB, dbName, userTable)
	if err != nil {
		return fmt.Errorf("getting PKs for %s: %w", userTable, err)
	}
	if len(userPKs) == 0 {
		return fmt.Errorf("table %s has no primary key", userTable)
	}

	// Build excluded-field lookup: table -> set of field names.
	excludedFieldSet := make(map[string]map[string]bool)
	for _, ef := range excludeFields {
		if excludedFieldSet[ef.Table] == nil {
			excludedFieldSet[ef.Table] = make(map[string]bool)
		}
		excludedFieldSet[ef.Table][ef.Field] = true
	}

	// Build replace-field lookup: table -> field -> replacement value.
	replaceFieldSet := make(map[string]map[string]string)
	for _, rf := range replaceFields {
		if replaceFieldSet[rf.Table] == nil {
			replaceFieldSet[rf.Table] = make(map[string]string)
		}
		replaceFieldSet[rf.Table][rf.Field] = rf.Value
	}

	// ---- Step 1: Extract Anagrafica rows for kept users ----
	log.Printf("Extracting %s rows for %d users...", userTable, len(keepUsers))
	userRows, userCols, err := queryFilteredByColumn(originDB, userTable, userColumn, keepUsers, excludedFieldSet, replaceFieldSet)
	if err != nil {
		return err
	}
	log.Printf("  -> %d rows from %s", len(userRows), userTable)

	// Build a set of kept PK values for the user table.
	keptPKs := make(map[string]map[string]bool)
	keptPKs[userTable] = extractPKSet(userRows, userCols, userPKs)

	if err := applySerials(originDB, userTable, replaceFieldSet, userRows, userCols); err != nil {
		return err
	}
	if err := writeInserts(f, userTable, userCols, userRows); err != nil {
		return err
	}

	// ---- Step 2: BFS-level extraction for dependent tables ----
	maxLevel := 0
	for _, lvl := range depLevels {
		if lvl > maxLevel {
			maxLevel = lvl
		}
	}

	for level := 1; level <= maxLevel; level++ {
		var tablesAtLevel []string
		for t, lvl := range depLevels {
			if lvl == level {
				tablesAtLevel = append(tablesAtLevel, t)
			}
		}
		sort.Strings(tablesAtLevel)

		for _, table := range tablesAtLevel {
			if schema.MatchesAny(table, emptyPatterns) {
				log.Printf("  -> skipping %s (empty table)", table)
				continue
			}
			rows, cols, err := queryDependentTable(originDB, dbName, table, g, keptPKs, excludedFieldSet, replaceFieldSet)
			if err != nil {
				return err
			}
			log.Printf("  -> %d rows from %s (level %d)", len(rows), table, level)

			pks, err := schema.GetPrimaryKeys(originDB, dbName, table)
			if err != nil {
				return err
			}
			if len(pks) > 0 && len(rows) > 0 {
				keptPKs[table] = extractPKSet(rows, cols, pks)
			}

			if err := applySerials(originDB, table, replaceFieldSet, rows, cols); err != nil {
				return err
			}
			if err := writeInserts(f, table, cols, rows); err != nil {
				return err
			}
		}
	}

	// ---- Step 3: Full copy for unrelated tables ----
	for _, table := range tables {
		if _, dependent := depLevels[table]; dependent {
			continue
		}
		if schema.MatchesAny(table, emptyPatterns) {
			log.Printf("  -> skipping %s (empty table)", table)
			continue
		}
		rows, cols, err := queryAllRows(originDB, table, excludedFieldSet, replaceFieldSet)
		if err != nil {
			return err
		}
		log.Printf("  -> %d rows from %s (full copy)", len(rows), table)
		if err := applySerials(originDB, table, replaceFieldSet, rows, cols); err != nil {
			return err
		}
		if err := writeInserts(f, table, cols, rows); err != nil {
			return err
		}
	}

	fmt.Fprintln(f, "SET FOREIGN_KEY_CHECKS=1;")
	return nil
}

// buildSelectList returns the SQL column list and the logical column names for a table.
// Excluded fields are selected as NULL (so the DB never reads the underlying data).
// Replaced fields are selected as a literal value (for anonymization).
func buildSelectList(db *sql.DB, table string, excluded map[string]bool, replaced map[string]string) (string, []string, error) {
	rows, err := db.Query("SELECT COLUMN_NAME, DATA_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? ORDER BY ORDINAL_POSITION", table)
	if err != nil {
		return "", nil, fmt.Errorf("listing columns for %s: %w", table, err)
	}
	defer rows.Close()

	var cols []string
	var parts []string
	for rows.Next() {
		var col, dataType string
		if err := rows.Scan(&col, &dataType); err != nil {
			return "", nil, err
		}
		cols = append(cols, col)
		if excluded[col] {
			parts = append(parts, fmt.Sprintf("NULL AS `%s`", col))
		} else if val, ok := replaced[col]; ok {
			if val == serialPlaceholder {
				// Serial columns are selected as NULL; values are filled post-query by applySerials.
				parts = append(parts, fmt.Sprintf("NULL AS `%s`", col))
			} else {
				parts = append(parts, fmt.Sprintf("%s AS `%s`", formatReplacementLiteral(val, dataType), col))
			}
		} else {
			parts = append(parts, "`"+col+"`")
		}
	}
	if err := rows.Err(); err != nil {
		return "", nil, err
	}
	return strings.Join(parts, ", "), cols, nil
}

// selectClause returns the select expression for a table, applying field exclusions and replacements if any.
func selectClause(db *sql.DB, table string, excludedFieldSet map[string]map[string]bool, replaceFieldSet map[string]map[string]string) (string, []string, error) {
	excluded := excludedFieldSet[table]
	replaced := replaceFieldSet[table]
	if len(excluded) > 0 || len(replaced) > 0 {
		return buildSelectList(db, table, excluded, replaced)
	}
	return "*", nil, nil // cols will be discovered by execQuery
}

// queryFilteredByColumn returns rows from table where column IN (values).
func queryFilteredByColumn(db *sql.DB, table, column string, values []string, excludedFieldSet map[string]map[string]bool, replaceFieldSet map[string]map[string]string) ([][]interface{}, []string, error) {
	if len(values) == 0 {
		return nil, nil, nil
	}
	sel, _, err := selectClause(db, table, excludedFieldSet, replaceFieldSet)
	if err != nil {
		return nil, nil, err
	}
	placeholders := make([]string, len(values))
	args := make([]interface{}, len(values))
	for i, v := range values {
		placeholders[i] = "?"
		args[i] = v
	}
	query := fmt.Sprintf("SELECT %s FROM `%s` WHERE `%s` IN (%s)",
		sel, table, column, strings.Join(placeholders, ","))
	return execQuery(db, query, args...)
}

// queryDependentTable queries a table filtering by FK relationships to already-extracted parent tables.
func queryDependentTable(
	db *sql.DB,
	dbName string,
	table string,
	g *schema.Graph,
	keptPKs map[string]map[string]bool,
	excludedFieldSet map[string]map[string]bool,
	replaceFieldSet map[string]map[string]string,
) ([][]interface{}, []string, error) {
	var conditions []string
	var args []interface{}

	for parentTable, pkSet := range keptPKs {
		edges := g.EdgesFromTo(table, parentTable)
		if len(edges) == 0 {
			continue
		}

		parentPKs, err := schema.GetPrimaryKeys(db, dbName, parentTable)
		if err != nil {
			return nil, nil, err
		}

		if len(parentPKs) == 1 {
			for _, e := range edges {
				if e.ToColumn == parentPKs[0] {
					vals := singleColumnValues(pkSet)
					if len(vals) == 0 {
						continue
					}
					ph := make([]string, len(vals))
					for i, v := range vals {
						ph[i] = "?"
						args = append(args, v)
					}
					conditions = append(conditions, fmt.Sprintf("`%s` IN (%s)", e.FromColumn, strings.Join(ph, ",")))
				}
			}
		} else {
			tuples := compositeValues(pkSet)
			if len(tuples) == 0 {
				continue
			}
			fkCols := make([]string, len(parentPKs))
			matched := true
			for i, pk := range parentPKs {
				found := false
				for _, e := range edges {
					if e.ToColumn == pk {
						fkCols[i] = e.FromColumn
						found = true
						break
					}
				}
				if !found {
					matched = false
					break
				}
			}
			if !matched {
				continue
			}
			var tupleStrs []string
			for _, tuple := range tuples {
				ph := make([]string, len(tuple))
				for i, v := range tuple {
					ph[i] = "?"
					args = append(args, v)
				}
				tupleStrs = append(tupleStrs, "("+strings.Join(ph, ",")+")")
			}
			colStr := make([]string, len(fkCols))
			for i, c := range fkCols {
				colStr[i] = "`" + c + "`"
			}
			conditions = append(conditions, fmt.Sprintf("(%s) IN (%s)",
				strings.Join(colStr, ","), strings.Join(tupleStrs, ",")))
		}
	}

	if len(conditions) == 0 {
		return nil, nil, nil
	}

	sel, _, err := selectClause(db, table, excludedFieldSet, replaceFieldSet)
	if err != nil {
		return nil, nil, err
	}
	query := fmt.Sprintf("SELECT %s FROM `%s` WHERE %s", sel, table, strings.Join(conditions, " OR "))
	return execQuery(db, query, args...)
}

// queryAllRows returns all rows from a table.
func queryAllRows(db *sql.DB, table string, excludedFieldSet map[string]map[string]bool, replaceFieldSet map[string]map[string]string) ([][]interface{}, []string, error) {
	sel, _, err := selectClause(db, table, excludedFieldSet, replaceFieldSet)
	if err != nil {
		return nil, nil, err
	}
	return execQuery(db, fmt.Sprintf("SELECT %s FROM `%s`", sel, table))
}

// execQuery runs a query and returns all rows as [][]interface{} plus column names.
func execQuery(db *sql.DB, query string, args ...interface{}) ([][]interface{}, []string, error) {
	rows, err := db.Query(query, args...)
	if err != nil {
		return nil, nil, fmt.Errorf("query %q: %w", truncateQuery(query), err)
	}
	defer rows.Close()

	cols, err := rows.Columns()
	if err != nil {
		return nil, nil, fmt.Errorf("getting columns: %w", err)
	}

	var result [][]interface{}
	for rows.Next() {
		vals := make([]interface{}, len(cols))
		ptrs := make([]interface{}, len(cols))
		for i := range vals {
			ptrs[i] = &vals[i]
		}
		if err := rows.Scan(ptrs...); err != nil {
			return nil, nil, fmt.Errorf("scanning row: %w", err)
		}
		result = append(result, vals)
	}
	return result, cols, rows.Err()
}

// writeInserts writes INSERT INTO statements for the given rows.
func writeInserts(f *os.File, table string, cols []string, rows [][]interface{}) error {
	if len(rows) == 0 {
		return nil
	}

	quotedCols := make([]string, len(cols))
	for i, c := range cols {
		quotedCols[i] = "`" + c + "`"
	}
	colList := strings.Join(quotedCols, ", ")

	for i := 0; i < len(rows); i += batchSize {
		end := i + batchSize
		if end > len(rows) {
			end = len(rows)
		}
		batch := rows[i:end]

		fmt.Fprintf(f, "INSERT INTO `%s` (%s) VALUES\n", table, colList)
		for j, row := range batch {
			vals := make([]string, len(row))
			for k, v := range row {
				vals[k] = formatValue(v)
			}
			sep := ","
			if j == len(batch)-1 {
				sep = ";"
			}
			fmt.Fprintf(f, "  (%s)%s\n", strings.Join(vals, ", "), sep)
		}
		fmt.Fprintln(f)
	}
	return nil
}

// formatValue converts a Go value to its SQL literal representation.
func formatValue(v interface{}) string {
	if v == nil {
		return "NULL"
	}
	switch val := v.(type) {
	case []byte:
		if len(val) == 0 {
			return "''"
		}
		return "'" + escapeString(string(val)) + "'"
	case string:
		return "'" + escapeString(val) + "'"
	case time.Time:
		return "'" + val.Format("2006-01-02 15:04:05") + "'"
	case int64:
		return fmt.Sprintf("%d", val)
	case float64:
		return fmt.Sprintf("%g", val)
	case bool:
		if val {
			return "1"
		}
		return "0"
	default:
		return "'" + escapeString(fmt.Sprintf("%v", val)) + "'"
	}
}

// applySerials replaces NULL placeholders with zero-padded serial numbers for
// columns whose replacement value is __CDUMP_SERIAL__. The width is derived from
// the column's CHARACTER_MAXIMUM_LENGTH in INFORMATION_SCHEMA.
func applySerials(db *sql.DB, table string, replaceFieldSet map[string]map[string]string, rows [][]interface{}, cols []string) error {
	replaced := replaceFieldSet[table]
	if len(replaced) == 0 || len(rows) == 0 {
		return nil
	}

	// Collect serial columns for this table.
	type serialCol struct {
		idx   int
		width int
	}
	var serials []serialCol

	colIdx := make(map[string]int, len(cols))
	for i, c := range cols {
		colIdx[c] = i
	}

	for col, val := range replaced {
		if val != serialPlaceholder {
			continue
		}
		idx, ok := colIdx[col]
		if !ok {
			continue
		}
		var maxLen int
		err := db.QueryRow(
			"SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.COLUMNS "+
				"WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = ? AND COLUMN_NAME = ?",
			table, col,
		).Scan(&maxLen)
		if err != nil {
			return fmt.Errorf("getting CHARACTER_MAXIMUM_LENGTH for %s.%s: %w", table, col, err)
		}
		serials = append(serials, serialCol{idx: idx, width: maxLen})
	}

	if len(serials) == 0 {
		return nil
	}

	// Fill in serial values.
	for i := range rows {
		for _, sc := range serials {
			rows[i][sc.idx] = fmt.Sprintf("%0*d", sc.width, i+1)
		}
	}
	return nil
}

// formatReplacementLiteral returns the SQL literal for a replacement value,
// taking the MySQL DATA_TYPE into account so that non-string types (BIT,
// integers, floats) are emitted without quotes.
func formatReplacementLiteral(value, dataType string) string {
	switch strings.ToLower(dataType) {
	case "bit":
		return fmt.Sprintf("b'%s'", value)
	case "tinyint", "smallint", "mediumint", "int", "integer", "bigint":
		return value
	case "float", "double", "decimal", "numeric", "real":
		return value
	default:
		return "'" + escapeString(value) + "'"
	}
}

// escapeString escapes special characters for MySQL string literals.
func escapeString(s string) string {
	var b strings.Builder
	for _, c := range s {
		switch c {
		case '\'':
			b.WriteString("\\'")
		case '\\':
			b.WriteString("\\\\")
		case '\n':
			b.WriteString("\\n")
		case '\r':
			b.WriteString("\\r")
		case 0:
			b.WriteString("\\0")
		case '\032':
			b.WriteString("\\Z")
		default:
			b.WriteRune(c)
		}
	}
	return b.String()
}

// extractPKSet builds a set of serialized PK values from rows.
func extractPKSet(rows [][]interface{}, cols []string, pkCols []string) map[string]bool {
	pkIndices := make([]int, len(pkCols))
	for i, pk := range pkCols {
		for j, col := range cols {
			if col == pk {
				pkIndices[i] = j
				break
			}
		}
	}

	set := make(map[string]bool, len(rows))
	for _, row := range rows {
		key := serializePK(row, pkIndices)
		set[key] = true
	}
	return set
}

// serializePK creates a string key from PK column values.
func serializePK(row []interface{}, pkIndices []int) string {
	parts := make([]string, len(pkIndices))
	for i, idx := range pkIndices {
		parts[i] = fmt.Sprintf("%v", normalizeValue(row[idx]))
	}
	return strings.Join(parts, "\x00")
}

// normalizeValue converts []byte to string for consistent comparison.
func normalizeValue(v interface{}) interface{} {
	if b, ok := v.([]byte); ok {
		return string(b)
	}
	return v
}

// singleColumnValues extracts individual values from a PK set (for single-column PKs).
func singleColumnValues(pkSet map[string]bool) []interface{} {
	vals := make([]interface{}, 0, len(pkSet))
	for k := range pkSet {
		vals = append(vals, k)
	}
	return vals
}

// compositeValues extracts tuple values from a PK set (for multi-column PKs).
func compositeValues(pkSet map[string]bool) [][]interface{} {
	var result [][]interface{}
	for k := range pkSet {
		parts := strings.Split(k, "\x00")
		tuple := make([]interface{}, len(parts))
		for i, p := range parts {
			tuple[i] = p
		}
		result = append(result, tuple)
	}
	return result
}

// truncateQuery shortens a query string for error messages.
func truncateQuery(q string) string {
	if len(q) > 120 {
		return q[:120] + "..."
	}
	return q
}
