package dump

import (
"fmt"
"os"
"strings"
)

// WriteSchemaSQL writes a schema.sql file with CREATE TABLE statements in the given order.
func WriteSchemaSQL(path string, tables []string, ddlMap map[string]string) error {
f, err := os.Create(path)
if err != nil {
return fmt.Errorf("creating %s: %w", path, err)
}
defer f.Close()

fmt.Fprintln(f, "-- Generated by cdump")
fmt.Fprintln(f, "SET FOREIGN_KEY_CHECKS=0;")
fmt.Fprintln(f, "SET NAMES utf8mb4;")
fmt.Fprintln(f)

for _, t := range tables {
ddl, ok := ddlMap[t]
if !ok {
continue
}
ddl = strings.TrimRight(ddl, ";")
fmt.Fprintf(f, "-- Table: %s\n", t)
fmt.Fprintf(f, "%s;\n\n", ddl)
}

fmt.Fprintln(f, "SET FOREIGN_KEY_CHECKS=1;")
return nil
}
